### PR TITLE
feat: allow to have config at pyproject.toml

### LINKED ISSUE #356: Reading configuration from pyproject.toml
### Context

It has become increasingly adopted the option to store the configuration of many tools inside the pyproject.toml file.

example for black:
https://ichard26-testblackdocs.readthedocs.io/en/refactor_docs/pyproject_toml.html

It would be amazing if mdformat could read it as well. And since mdformat already supports toml format configurations, it would be trivial to implement looking for the configuration in the `tool.mdformat` section of one's pyproject.toml file

```
# .mdformat.toml
#
# This file shows the default values and is equivalent to having
# no configuration file at all. Change the values for non-default
# behavior.
#
wrap = "keep"       # possible values: {"keep", "no", INTEGER}
number = false      # possible values: {false, true}
end_of_line = "lf"  # possible values: {"lf", "crlf", "keep"}
```

```
# pyproject.toml

#.......
[tool.mdformat]
wrap = "keep"       # possible values: {"keep", "no", INTEGER}
number = false      # possible values: {false, true}
end_of_line = "lf"  # possible values: {"lf", "crlf", "keep"}
```

### Proposal

I think an approach would be ...

modify this function:
https://github.com/executablebooks/mdformat/blob/2b3145d43909b15cbf84bb2c16705d24cecf177a/src/mdformat/_conf.py#L26-L44

so that:

- it first looks for the `.mdformat.toml`
  - if found use it
- if it is not found, look for `pyproject.toml`
  - if found, look for a `tool.mdformat` section
    - if found use that as if it was the contents of `.mdformat.toml`

 LMK what you think, I could make it a PR later in the week

### Tasks and updates

- [ ] implement changes
- [ ] add unit testing
- [ ] add documentation

### PR DESCRIPTION
**Pull request by tinovyatkin**
This PR allows to specify options at `pyproject.toml` file (at `tool.mdformat` section) as most modern Python tooling (black, ruff, etc) doing.

Fixes #356

### CODE REVIEW

**Comment by tinovyatkin** [comment]
@hukkin could you take a look please?

**Comment by dynobo** [comment]
FYI: While I'd love to see this integrated in `mdformat` as well, in the meanwhile I learned through #379 about the plugin [`mdformat-pyproject`](https://github.com/csala/mdformat-pyproject), which serves me well in the meanwhile.

**Review by Borda — APPROVED** [review]

**Comment by sanmai-NL** [comment]
@hukkin ping

**Comment by hukkin** [comment]
I'm rejecting this, please see https://github.com/executablebooks/mdformat/issues/356#issuecomment-1246596603

Thanks anyways!

There is a plugin for those interested in this feature https://pypi.org/project/mdformat_pyproject/

**Pull request closed without merging**
