### PR TITLE
Read configuration from .mdformat.toml

### PR DESCRIPTION
**Pull request by hukkin**
Closes https://github.com/executablebooks/mdformat/issues/263

### CODE REVIEW

**Comment by rpdelaney** [comment]
Nice! Thank you! I will play around with this soon.

**Comment by hukkin** [comment]
> Nice! Thank you!

You're very welcome! Thank you for the issue.

> I will play around with this soon.

Cool. Let me know if you experience any issues or have feedback. As of now the feature is unreleased, so you will need to install with `pip install git+https://github.com/executablebooks/mdformat`, or if using pre-commit, set `rev` to a commit hash (`f0724009c4f58ff33d3180cd931e6d5eb078f86f`) instead of a version tag.

**Comment by rpdelaney** [comment]
I'm not able to get the `wrap` option working in the config file. The other options are respected though. Here's my `.mdformat.toml`:

```toml
# .mdformat.toml
#
wrap = "80"       # possible values: {"keep", "no", INTEGER}
number = false      # possible values: {false, true}
end_of_line = "lf"  # possible values: {"lf", "crlf"}
```

```console
$ mdformat --version
mdformat 0.7.9 (mdformat_tables: 0.4.1, mdformat_gfm: 0.3.3, mdformat_toc: 0.3.0)
$ markdownlint rules.md
rules.md:586:81 MD013/line-length Line length [Expected: 80; Actual: 205]
$ mdformat rules.md
$ markdownlint rules.md
rules.md:586:81 MD013/line-length Line length [Expected: 80; Actual: 205]
$ mdformat --wrap 80 rules.md
$ markdownlint rules.md
$
```

**Comment by hukkin** [comment]
Oh, I assume that is because your wrap width is a string
```toml
wrap = "80" 
```
but is expected to be integer
```toml
wrap = 80
```

I just made a PR that validates all conf values (https://github.com/executablebooks/mdformat/pull/267) so this should be caught by the validation then.

**Pull request merged**
